import localFont from "next/font/local";
import "../styles/globals.css";
import "../styles/background.css";

const geistSans = localFont({
  src: "../styles/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../styles/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-wrap md:items-center justify-center w-screen h-screen font-[family-name:var(--font-geist-sans)]">
          <div className="container overflow-hidden w-3/4 h-1/2 md:1/2 md:h-3/4 lg:w-1/3 mt-24 md:mt-0 bg-slate-600 text-white shadow-xl shadow-black">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
